# Site settings
title: Recipes
email: 
description: An amazing recipe database!
start_url: "http://hcornelison.dev/cooks/index.html"

#comment out while debugging locally
baseurl: "http://hcornelison.dev/cooks"

#uncomment for local debugging!
#baseurl: "" 
language: "en"
lang_direction: "ltr"
github_username:  hcornelison

# Template colors used site-wide via css
colors:
  dark-mode:
    background-color: "#2D2727"
    primary-text-color: "#fff"
    secondary-text-color: "#fff"
    link-color: "#ff851b"
    menu-color: "#181616"
    accent-color: "#3e3535"
  light-mode:
    background-color: "#f6efec"
    primary-text-color: "#000"
    secondary-text-color: "#714e79"
    link-color: "#418362"
    menu-color: "#c7a8cc"
    accent-color: "#cad5c8"

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true
  tips:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

translation:
  en:
    components: "Components"
    ingredients: "Ingredients"
    directions: "Directions"
    category: "Category"
    categories: "Categories"
    nutritional_information: "Nutritional Information"
    component_based: 'This is a <strong class="preffered-color">component-based recipe</strong>.'
    search: "Search"
    blog: "Blog"
    subscribe: "Subscribe"
    home: "Home"
    tips: "Tips"
    theme: "Theme"
    notes: "Notes"
    yield: "Servings:"
    preptime: "Prep Time:"
    cooktime: "Cooking Time:"
